Repository beatrizheav/FinanceTracker, pull requests merged in 2025-03, with the labels that each got.

#30 PR-Sprint-1/issue#1---set up development environment
  CODEOWNERS
  README.md
  client/.gitignore
  client/README.md
  client/app.json
  client/app/(tabs)/_layout.tsx
  client/app/(tabs)/explore.tsx
  client/app/(tabs)/index.tsx
  client/app/+not-found.tsx
  client/app/_layout.tsx
  client/assets/fonts/SpaceMono-Regular.ttf
  client/assets/images/adaptive-icon.png
  client/assets/images/favicon.png
  client/assets/images/icon.png
  client/assets/images/partial-react-logo.png
  client/assets/images/react-logo.png
  client/assets/images/react-logo@2x.png
  client/assets/images/react-logo@3x.png
  client/assets/images/splash-icon.png
  client/components/Collapsible.tsx
  client/components/ExternalLink.tsx
  client/components/HapticTab.tsx
  client/components/HelloWave.tsx
  client/components/ParallaxScrollView.tsx
  client/components/ThemedText.tsx
  client/components/ThemedView.tsx
  client/components/__tests__/ThemedText-test.tsx
  client/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  client/components/ui/IconSymbol.ios.tsx
  client/components/ui/IconSymbol.tsx
  client/components/ui/TabBarBackground.ios.tsx
  client/components/ui/TabBarBackground.tsx
  client/constants/Colors.ts
  client/hooks/useColorScheme.ts
  client/hooks/useColorScheme.web.ts
  client/hooks/useThemeColor.ts
  client/package-lock.json
  client/package.json
  client/scripts/reset-project.js
  client/tsconfig.json
Labels: good first issue

#31 PR-Sprint-1/Issue#2---Add global styles
  client/app/(tabs)/_layout.tsx
  client/app/(tabs)/explore.tsx
  client/app/(tabs)/index.tsx
  client/app/+not-found.tsx
  client/app/_layout.js
  client/app/_layout.tsx
  client/app/index.js
  client/app/main.js
  client/assets/fonts/SpaceMono-Regular.ttf
  client/components/Collapsible.tsx
  client/components/ExternalLink.tsx
  client/components/HapticTab.tsx
  client/components/HelloWave.tsx
  client/components/ParallaxScrollView.tsx
  client/components/ThemedText.tsx
  client/components/ThemedView.tsx
  client/components/__tests__/ThemedText-test.tsx
  client/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  client/components/ui/IconSymbol.ios.tsx
  client/components/ui/IconSymbol.tsx
  client/components/ui/TabBarBackground.ios.tsx
  client/components/ui/TabBarBackground.tsx
  client/constants/Colors.ts
  client/hooks/useColorScheme.ts
  client/hooks/useColorScheme.web.ts
  client/hooks/useThemeColor.ts
  client/package-lock.json
  client/package.json
  client/scripts/reset-project.js
  client/styles/colorsTheme.js
  client/styles/fontsTheme.js
  client/styles/general.js
  client/tsconfig.json
  package-lock.json
Labels: enhancement

#32 PR-Sprint-1/issue#5---create-button-component
  client/components/CustomButton.js
  client/styles/colorsTheme.js
  client/styles/components/custom-button.js
Labels: enhancement

#38 PR-Sprint-1/issue#10---Create Reusable Month Picker Component
  client/components/DatePickerDropdown.js
  client/components/__tests__/DatePickerDropdown.test.js
  client/constants/getDate.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/styles/components/date-picker-dropdown.js
Labels: enhancement

#41 PR-Sprint-2/issue#7.1-8.1---add porperty color to title and text component
  client/components/ActivityDisplay.js
  client/components/BalanceDisplay.js
  client/components/CustomButton.js
  client/components/CustomText.js
  client/components/CustomTitle.js
  client/components/Header.js
  client/components/__test__/ActivityDisplay.test.js
  client/package-lock.json
  client/package.json
  client/styles/colorsTheme.js
  client/styles/components/activity-display.js
  client/styles/components/balance-display.js
  client/styles/components/custom-button.js
  client/styles/components/header.js
  client/styles/fontsTheme.js
Labels: enhancement, Component

#43 Sprint-1/issue#4 create input component
  client/.gitignore
  client/app.json
  client/app/main.js
  client/assets/avatars/1.png
  client/assets/avatars/10.png
  client/assets/avatars/11.png
  client/assets/avatars/12.png
  client/assets/avatars/13.png
  client/assets/avatars/14.png
  client/assets/avatars/15.png
  client/assets/avatars/16.png
  client/assets/avatars/2.png
  client/assets/avatars/3.png
  client/assets/avatars/4.png
  client/assets/avatars/5.png
  client/assets/avatars/6.png
  client/assets/avatars/7.png
  client/assets/avatars/8.png
  client/assets/avatars/9.png
  client/assets/avatars/add.png
  client/components/AvatarPicker.js
  client/components/ColorPicker.js
  client/components/CustomButton.js
  client/components/CustomInput.js
  client/components/DatePicker.js
  client/components/DropdownSelect.js
  client/components/IconPicker.js
  client/components/ImagePicker.js
  client/components/MenuDropdown.js
  client/components/__test__/BalanceDisplay.test.js
  client/components/__test__/ColorPicker.test.js
  client/components/__test__/CustomInput.test.js
  client/components/__test__/DatePicker.test.js
  client/components/__test__/DropdownSelect.test.js
  client/components/__test__/ImagePicker.test.js
  client/components/__test__/MenuDropdown.test.js
  client/constants/avatars.js
  client/constants/categoryData.js
  client/package-lock.json
  client/package.json
  client/styles/colorsTheme.js
  client/styles/components/avatar-picker.js
  client/styles/components/color-picker.js
  client/styles/components/dropdown-select.js
  client/styles/components/icon-picker.js
  client/styles/components/image-picker.js
  client/styles/components/inputs.js
  client/styles/components/menu-dropdown.js
Labels: Component

#44 Sprint 2/issue#14 create lateral menu component
  .DS_Store
  client/assets/images/Sophie.png
  client/components/SideMenu.js
  client/components/__tests__/SideMenu.test.js
  client/constants/sideMenuSizes.js
  client/jest.config.js
  client/jest.setup.js
  client/styles/components/side-menu.js
Labels: enhancement

#46 PR-Sprint-2/issue#15---create modal component for expense information
  client/components/ModalDetail.js
  client/components/ModalExpense.js
  client/components/__test__/ModalExpense.test.js
  client/constants/expenseData.js
  client/package-lock.json
  client/styles/components/image-picker.js
  client/styles/components/modal-detail.js
  client/styles/components/modal-expense.js
Labels: enhancement

#50 PR-Sprint-3/issue#21---splash-screen
  client/app.json
  client/app/index.js
  client/assets/images/LogoSplash.png
  client/assets/images/PigLogo.png
  client/assets/images/Sophie.png
  client/components/CustomText.js
  client/components/SideMenu.js
  client/package-lock.json
  client/package.json
  client/styles/general.js
Labels: enhancement

#51 PR-Sprint-3/issue#14.1---Edit-lateral-menu-component
  client/components/Header.js
  client/components/SideMenu.js
  client/styles/components/header.js
  client/styles/components/side-menu.js
Labels: bug

#53 Sprint 3/issue#18 create bottom sheet for creatingediting an expense
  client/components/BSCategory.js
  client/components/BSExpense.js
  client/components/CustomCheckbox.js
  client/components/CustomInput.js
  client/components/DatePicker.js
  client/components/DropdownCategory.js
  client/components/ImagePicker.js
  client/constants/expenseData.js
  client/package-lock.json
  client/package.json
  client/styles/components/bs-expense.js
  client/styles/components/custom-checkbox.js
  client/styles/components/dropdown-category.js
Labels: enhancement
