Repository beatrizheav/FinanceTracker, pull requests merged in 2025-05, with the labels that each got.

#111 PR-Sprint-7/issue#49---create endpoint to fetch user categories
  client/app/categories.js
  client/components/BSCategory.js
  client/components/CategoryIcon.js
  client/components/ModalCategory.js
  client/styles/screens/categories.js
Labels: Backend, Get

#115 PR - Merge Sprint 7 Changes from staging to main
  backend/.gitignore
  backend/config/firebaseConfig.js
  backend/controllers/categoriesController.js
  backend/controllers/expenseController.js
  backend/controllers/incomeController.js
  backend/controllers/userController.js
  backend/middleware/multer.js
  backend/package-lock.json
  backend/package.json
  backend/queries/createCategory.sql
  backend/server.js
  client/api/apiClient.js
  client/app/categories.js
  client/app/expenses.js
  client/app/home.js
  client/components/BSCategory.js
  client/components/BSExpense.js
  client/components/BSIncome.js
  client/components/CategoryIcon.js
  client/components/ModalCategory.js
  client/hooks/useFormValidation.js
  client/hooks/validateIncomeData.js
  client/hooks/validationRules.js
  client/styles/components/bs-expense.js
  client/styles/screens/categories.js
Labels: enhancement, Backend

#112 PR-Sprint-7/Issue#48---create endpoint to fetch user expenses
  backend/controllers/categoriesController.js
  backend/controllers/expenseController.js
  backend/server.js
  client/app/expenses.js
  client/components/ActivityDisplay.js
  client/components/BSExpense.js
  client/components/ModalExpense.js
Labels: enhancement

#113 PR - Sprint 7/issue#47 create endpoint to fetch user incomes
  backend/controllers/incomeController.js
  backend/server.js
  client/app/Incomes.js
  client/components/BSIncome.js
  client/components/ModalIncome.js
Labels: Backend

#116 PR-Sprint-8/Issue#51-Load User Info from AsyncStorage and Display in Side Menu & Home Header
  backend/controllers/userController.js
  client/components/Header.js
  client/components/SideMenu.js
  client/hooks/getAvatar.js
  client/hooks/useUser.js
  client/styles/components/header.js
  client/styles/components/side-menu.js
Labels: enhancement

#117 PR - Sprint 8/issue#50 Update balance display on change
  backend/controllers/incomeController.js
  client/app/home.js
Labels: bug, Backend, Update

#118 Sprint-8/Issue#45---create an endpoint to edit a category and implement frontend integration
  backend/controllers/categoriesController.js
  backend/server.js
  client/app/categories.js
  client/components/ActivityDisplay.js
  client/components/BSCategory.js
Labels: enhancement

#121 PR-Sprint-8/Issue#54---Refactor Categories Endpoint to Return Dynamic Expense Totals
  backend/controllers/categoriesController.js
  client/app/categories.js
  client/components/ActivityDisplay.js
  client/components/ModalCategory.js
Labels: bug, Backend

#122 PR-Sprint-8/Issue#44---Create an Endpoint to Edit an Expense and Implement Frontend Integration
  backend/controllers/expenseController.js
  backend/server.js
  client/app/expenses.js
  client/components/BSExpense.js
  client/components/ModalExpense.js
Labels: Backend

#123 PR-Sprint-8/Issue#53-- Fixed Transactions, Expenses and Incomes in Monthly Balance
  backend/controllers/expenseController.js
  backend/controllers/incomeController.js
Labels: bug

#129 PR-Sprint-8/issue#43---create an endpoint to edit an income and implement frontend integration
  backend/controllers/incomeController.js
  backend/server.js
  client/app/Incomes.js
  client/components/BSIncome.js
  client/components/ModalIncome.js
  client/hooks/validationRules.js
Labels: Backend, Update

#132 PR-Sprint-8/Issue#55--- Delete Income Entry
  backend/controllers/incomeController.js
  backend/server.js
  client/app/Incomes.js
  client/components/ModalIncome.js
Labels: Backend

#131 PR-Sprint-8/issue#58--Connect horizontal scrollview with category expense data
  client/app/categories.js
  client/app/home.js
  client/components/ExpensesChart.js
  client/components/ExpensesScrollview.js
  client/hooks/useCategories.js
Labels: enhancement, Backend

#133 PR-Sprint 8/issue#56 delete expense entry
  backend/controllers/expenseController.js
  backend/server.js
  client/app/expenses.js
  client/components/ModalExpense.js
Labels: Backend, Delete

#136 Sprint-9/Issue#57---Safely Delete Categories with Task Reassignment
  backend/controllers/categoriesController.js
  backend/server.js
  client/app/categories.js
  client/components/ModalCategory.js
Labels: enhancement, Backend

#139 PR-Sprint-9/Issue#61---Allow saving past date while editing in calendar
  client/components/DatePicker.js
Labels: bug

#140 PR - Sprint-9/Issue#60---Implement Logout Functionality
  client/api/apiClient.js
  client/app/Incomes.js
  client/app/categories.js
  client/app/expenses.js
  client/app/home.js
  client/app/index.js
  client/components/SideMenu.js
  client/hooks/useAuthGuard.js
  client/utils/auth.js
Labels: Backend, Update

#141 PR - Sprint-9/Issue#62---Show all records and sort them by date
  client/app/Incomes.js
  client/app/expenses.js
Labels: Backend

#142 PR-Sprint-9/issue#59---display recent activity incomes expenses in home scrollview
  client/app/home.js
  client/components/ModalCategory.js
  client/components/ModalExpense.js
  client/components/ModalIncome.js
  client/components/RecentActivity.js
  client/hooks/useExpenseAndIncomes.js
  client/styles/screens/home.js
Labels: Backend, Get

#145 PR-Sprint-9/issue#63---fix message when user has no recent activity
  client/components/RecentActivity.js
Labels: fix
