Repository beatrizheav/FinanceTracker, pull requests merged in 2025-04, with the labels that each got.

#55 PR-Sprint-4/issue#22---create-login-screen
  client/app/__tests__/LoginScreen.test.js
  client/app/loginScreen.js
  client/app/registration.js
  client/components/CustomInput.js
  client/constants/expenses.js
  client/hooks/useFormValidation.js
  client/hooks/validationRules.js
  client/styles/components/inputs.js
  client/styles/general.js
  client/styles/screens/login-screen.js
  client/styles/screens/registration.js
Labels: Screen

#59 PR-Sprint-3/issue#25---create income screen
  client/app/Incomes.js
  client/app/__tests__/Incomes.test.js
  client/app/registration.js
  client/components/ActivityDisplay.js
  client/components/BSIncome.js
  client/components/CustomButton.js
  client/components/CustomText.js
  client/components/ModalIncome.js
  client/components/__tests__/ActivityDisplay.test.js
  client/components/__tests__/CustomButton.test.js
  client/components/__tests__/CustomText.test.js
  client/constants/income.js
  client/constants/incomesData.js
  client/styles/components/add-button.js
  client/styles/components/modal-income.js
  client/styles/screens/incomes.js
Labels: enhancement, Screen

#64 Sprint-3/issue#24---create home screen
  client/app/Incomes.js
  client/app/__tests__/home.test.js
  client/app/home.js
  client/components/AddButton.js
  client/components/BSCategory.js
  client/components/BSExpense.js
  client/components/BSIncome.js
  client/components/DatePickerDropdown.js
  client/components/Header.js
  client/components/MenuDropdown.js
  client/components/ModalCategory.js
  client/components/ModalExpense.js
  client/components/ModalIncome.js
  client/components/RecentActivity.js
  client/constants/expenseData.js
  client/constants/expensesData.js
  client/constants/incomesData.js
  client/package-lock.json
  client/package.json
  client/styles/components/add-button.js
  client/styles/components/bs-expense.js
  client/styles/components/date-picker-dropdown.js
  client/styles/components/expenses-scrollview.js
  client/styles/components/header.js
  client/styles/components/recent-activity.js
  client/styles/general.js
  client/styles/screens/home.js
Labels: enhancement

#65 PR-Sprint-3/issue#27---create-categories-screen
  client/app/__tests__/LoginScreen.test.js
  client/app/__tests__/categories.test.js
  client/app/categories.js
  client/app/login.js
  client/constants/categories.js
  client/styles/screens/categories.js
Labels: Screen

#70 Sprint 4/issue#28 remove custom title component and apply custom text
  client/app/Incomes.js
  client/app/login.js
  client/components/AvatarPicker.js
  client/components/BSCategory.js
  client/components/BSExpense.js
  client/components/BSIncome.js
  client/components/BalanceDisplay.js
  client/components/CategoryExpense.js
  client/components/ColorPicker.js
  client/components/CustomInput.js
  client/components/CustomTitle.js
  client/components/DatePicker.js
  client/components/DatePickerDropdown.js
  client/components/DropdownCategory.js
  client/components/ExpensesChart.js
  client/components/Header.js
  client/components/IconPicker.js
  client/components/ImagePicker.js
  client/components/ModalDetail.js
  client/components/ModalExpense.js
  client/components/ModalIncome.js
  client/components/SideMenu.js
  client/components/__tests__/CategoryExpense.test.js
  client/constants/categories.js
  client/jest.setup.js
  client/styles/components/balance-display.js
  client/styles/components/header.js
  client/styles/components/side-menu.js
Labels: enhancement

#71 Sprint-4/issue#29---Add Navigation Using Expo Router
  client/app/index.js
  client/app/login.js
  client/app/registration.js
  client/components/CustomInput.js
  client/components/RecentActivity.js
  client/components/SideMenu.js
Labels: enhancement

#72 Sprint-4/Issue#30 --- Resolve style conflicts across screens
  client/app/Incomes.js
  client/app/categories.js
  client/app/expenses.js
  client/app/home.js
  client/app/login.js
  client/app/registration.js
  client/components/CustomInput.js
  client/components/Header.js
  client/components/RecentActivity.js
  client/components/SideMenu.js
  client/constants/expensesData.js
  client/styles/components/header.js
  client/styles/components/recent-activity.js
  client/styles/screens/categories.js
  client/styles/screens/expense.js
  client/styles/screens/incomes.js
  client/styles/screens/login-screen.js
  client/styles/screens/registration.js
Labels: bug

#76 PR-Sprint-4/Issue#32--- Fix sintax error
  client/app/Incomes.js
  client/app/categories.js
  client/app/expenses.js
  client/components/CustomInput.js
  client/constants/incomesData.js
  client/styles/screens/categories.js
  client/styles/screens/expense.js
  client/styles/screens/incomes.js
Labels: bug

#77 PR - Sprint-4/Issue#33---Initialize project
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
Labels: enhancement

#83 Sprint-5/issue#34---create folder structure for routes controllers and models
  README.md
  backend/config/db.js
  backend/controllers/example.js
  backend/package-lock.json
  backend/package.json
  backend/queries/example.js
  backend/schema.sql
  backend/server.js
  client/README.md
Labels: enhancement

#84 PR-Sprint-5/Issue#35 - MySQL Database Setup and Connection Configuration
  backend/.gitignore
  backend/config/db.js
  backend/controllers/example.js
  backend/controllers/userController.js
  backend/package-lock.json
  backend/package.json
  backend/queries/createCategorie.sql
  backend/queries/createExpense.sql
  backend/queries/createIncome.sql
  backend/queries/createUser.sql
  backend/schema.sql
  backend/server.js
Labels: Backend

#85 Sprint-5/Issue#38--- iOS Keyboard Covers Input Fields in Forms
  client/app/login.js
  client/app/registration.js
  client/styles/screens/registration.js
Labels: enhancement

#88 PR-Sprint-5/Issue#37 - User Registration API and Frontend Integration
  backend/controllers/userController.js
  backend/server.js
  client/api/apiClient.js
  client/app/index.js
  client/app/registration.js
  client/package-lock.json
  client/package.json
Labels: Backend

#91 PR-Sprint-5/issue#36---create login controller backend api and integrate in frontend
  backend/.env.template
  backend/controllers/userController.js
  backend/server.js
  client/.env.template
  client/.gitignore
  client/api/apiClient.js
  client/app/login.js
  client/babel.config.js
  client/package-lock.json
  client/package.json
Labels: Backend

#93 PR-Sprint-5/Issue#42 - Create endpoint to fetch user categories and display in dropdown
  backend/controllers/categoriesController.js
  backend/middleware/authenticate
  backend/server.js
  client/api/apiClient.js
  client/components/DropdownCategory.js
  client/constants/categoryData.js
Labels: Backend

#94 PR-Sprint 5/issue#40 - Create add income endpoint and Implement Frontend Integration.
  backend/controllers/incomeController.js
  backend/server.js
  client/.gitignore
  client/babel.config.js
  client/components/BSIncome.js
  client/components/CustomCheckbox.js
  client/hooks/validateIncomeData.js
  client/hooks/validationRules.js
  client/package-lock.json
Labels: enhancement

#103 PR-Sprint-6/issue#41---create an endpoint to add a category and implement frontend integration
  backend/controllers/categoriesController.js
  backend/queries/createCategory.sql
  backend/server.js
  client/components/BSCategory.js
  client/hooks/useFormValidation.js
  client/hooks/validationRules.js
Labels: Backend

#106 fix: fix BottomSheetCategory error to close
  client/app/categories.js
Labels: bug

#107 PR - Sprint-5/Issue#39---endpoint to add expense and implement frontend integration
  backend/.gitignore
  backend/config/firebaseConfig.js
  backend/controllers/expenseController.js
  backend/controllers/userController.js
  backend/middleware/multer.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  client/api/apiClient.js
  client/app/expenses.js
  client/components/BSExpense.js
  client/hooks/useFormValidation.js
  client/hooks/validationRules.js
Labels: enhancement

#110 PR-Sprint-7/Issue#52---fix-bug-acitivty-indicator-BSExpense
  client/components/BSExpense.js
  client/styles/components/bs-expense.js
Labels: bug
